//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADOL.APP.CurrentAccountService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApuestasDeUsuario
    {
        public int ID { get; set; }
        public string Token { get; set; }
        public decimal Amount { get; set; }
        public int ApuestaDeportivaID { get; set; }
        public Nullable<bool> Acierto { get; set; }
        public string BetType { get; set; }
        public decimal BetPrice { get; set; }
    
        public virtual ApuestasDeportiva ApuestasDeportiva { get; set; }
    }
}
