//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toqueyva.Framework.CurrentAccountService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventosDeportivo
    {
        public EventosDeportivo()
        {
            this.ApuestasDeUsuarios = new HashSet<ApuestasDeUsuario>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Codigo { get; set; }
        public bool Activo { get; set; }
        public System.DateTime Inicio { get; set; }
        public System.DateTime Fin { get; set; }
        public int DeporteID { get; set; }
    
        public virtual ICollection<ApuestasDeUsuario> ApuestasDeUsuarios { get; set; }
        public virtual Deporte Deporte { get; set; }
    }
}
