//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADOL.APP.CurrentAccountService.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ADOLDBEntities : DbContext
    {
        public ADOLDBEntities()
            : base("name=ADOLDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SportBet> SportBets { get; set; }
        public DbSet<SportEvent> SportEvents { get; set; }
        public DbSet<Sport> Sports { get; set; }
        public DbSet<UserBet> UserBets { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
