//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADOL.APP.CurrentAccountService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportEvent
    {
        public SportEvent()
        {
            this.SportBets = new HashSet<SportBet>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public bool Active { get; set; }
        public System.DateTime Init { get; set; }
        public System.DateTime End { get; set; }
        public string Home { get; set; }
        public string Away { get; set; }
        public int SportID { get; set; }
        public string LeagueCode { get; set; }
        public string CountryCode { get; set; }
    
        public virtual ICollection<SportBet> SportBets { get; set; }
        public virtual Sport Sport { get; set; }
    }
}
