//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADOL.APP.CurrentAccountService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportEvent
    {
        public SportEvent()
        {
            this.SportBets = new HashSet<SportBet>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public bool Active { get; set; }
        public System.DateTime Init { get; set; }
        public System.DateTime End { get; set; }
        public string Home { get; set; }
        public string Away { get; set; }
        public int SportID { get; set; }
        public string LeagueCode { get; set; }
        public string CountryCode { get; set; }
    
        public virtual ICollection<SportBet> SportBets { get; set; }
        public virtual Sport Sport { get; set; }
    }
}
