//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADOL.APP.CurrentAccountService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportBet
    {
        public SportBet()
        {
            this.UserBets = new HashSet<UserBet>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
        public decimal Odd1 { get; set; }
        public Nullable<decimal> Odd2 { get; set; }
        public Nullable<decimal> Odd3 { get; set; }
        public Nullable<decimal> Odd4 { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public int SportEventID { get; set; }
    
        public virtual SportEvent SportEvent { get; set; }
        public virtual ICollection<UserBet> UserBets { get; set; }
    }
}
