USE [master]
GO

/****** Object:  Database [GOL]    Script Date: 2/20/2015 12:43:34 PM ******/
CREATE DATABASE [GOL]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GOL', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\GOL.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'GOL_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\GOL_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [GOL] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GOL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GOL] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GOL] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GOL] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GOL] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GOL] SET ARITHABORT OFF 
GO

ALTER DATABASE [GOL] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GOL] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [GOL] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GOL] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GOL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GOL] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GOL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GOL] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GOL] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GOL] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GOL] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GOL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GOL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GOL] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GOL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GOL] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GOL] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GOL] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GOL] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GOL] SET  MULTI_USER 
GO

ALTER DATABASE [GOL] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GOL] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GOL] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GOL] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [GOL] SET  READ_WRITE 
GO


