//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADOL.APP.CurrentAccountService.BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBet
    {
        public int ID { get; set; }
        public string Token { get; set; }
        public int SportBetID { get; set; }
        public decimal Amount { get; set; }
        public string MatchCode { get; set; }
        public bool Hit { get; set; }
        public string BetType { get; set; }
        public decimal BetPrice { get; set; }
        public string LinkedCode { get; set; }
    
        public virtual SportBet SportBet { get; set; }
    }
}
