//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADOL.APP.CurrentAccountService.BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserBets = new HashSet<UserBet>();
        }
    
        public int ID { get; set; }
        public string UID { get; set; }
        public string NickName { get; set; }
        public string SessionToken { get; set; }
        public string LaunchToken { get; set; }
        public decimal Balance { get; set; }
    
        public virtual ICollection<UserBet> UserBets { get; set; }
    }
}
