INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Cup','1008','396','1',1,'16492','FBBLR Cup-14','Belarus')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Ligue 2','1022','408','1',1,'16768','FBFRA Ligue 2-14','France')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Ligue 1','1022','408','1',1,'16769','FBFRA Ligue 1-14','France')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Svenska Cupen','1053','410','1',1,'16780','FBSWE Svenska Cupen-14','Sweden')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Ascenso MX','1039','413','1',1,'16819','FBMEX Ascenso MX-14','Mexico')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Eerste Divisie','1016','407','1',1,'16820','FBDUT Eerste Divisie-14','Holland')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('A-League','1004','454','1',1,'16821','FBAUS A-League-14','Australia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Liga MX','1039','413','1',1,'16822','FBMEX Liga MX-14','Mexico')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Eredivisie','1016','407','1',1,'16823','FBDUT Eredivisie-14','Holland')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Superliga','1015','378','1',1,'16824','FBDEN Superliga-14','Denmark')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Bundesliga','1005','383','1',1,'16828','FBAUT Bundesliga-14','Austria')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('1. HNL','1012','415','1',1,'16843','FBCRO 1. HNL-14','Croatia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Extraliga','1061','468','1',1,'16848','ICCZE Extraliga-14','Czech Republic')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Premier League','1018','382','1',1,'16882','FBENG Premier League-14','England')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Championship','1018','382','1',1,'16883','FBENG Championship-14','England')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Premiership','1050','449','1',1,'16885','FBSCO Premier League-14','Scotland')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('League One','1018','382','1',1,'16887','FBENG League One-14','England')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('League Two','1018','382','1',1,'16888','FBENG League Two-14','England')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Championship','1050','449','1',1,'16889','FBSCO Championship-14','Scotland')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('League Two','1050','449','1',1,'16890','FBSCO League Two-14','Scotland')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('League One','1050','449','1',1,'16891','FBSCO League One-14','Scotland')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Challenge League','1054','451','1',1,'16893','FBSWI Challenge League-14','Switzerland')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Super League','1054','451','1',1,'16894','FBSWI Super League-14','Switzerland')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Ekstraklasa','1078','386','1',1,'16895','FBPOL Ekstraklasa-14','Poland')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Super Liga','1134','428','1',1,'16898','FBSRB Super Liga-14','Serbia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Ligue 1','1165','469','1',1,'16899','FBALG Ligue 1-14','Algeria')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Premier League','1049','368','1',1,'16901','FBRUS Premier League-14','Russia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('1st Division','1015','378','1',1,'16907','FBDEN 1. Div-14','Denmark')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Pro League','1146','462','1',1,'16909','FBKSA Pro League-14','Saudi Arabia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('A PFG','1010','363','1',1,'16911','FBBUL A PFG-14','Bulgaria')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('NHL','1854','459','1',1,'16942','ICUSA NHL-14','USA')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('2. Bundesliga','1024','446','1',1,'16944','FBGER 2. Bundesliga-14','Germany')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Bundesliga','1024','446','1',1,'16945','FBGER Bundesliga-14','Germany')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Liga Nacional','1199','478','1',1,'16954','FBGUA Liga Nacional-14','Guatemala')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('NB I','1026','412','1',1,'16957','FBHUN NB I-14','Hungary')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Czech Liga','1014','468','1',1,'16958','FBCZE Czech Liga-14','Czech Republic')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('2. liga','1014','468','1',1,'16959','FBCZE 2. Liga-14','Czech Republic')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Premier League','1057','444','1',1,'16975','FBWAL Premier League-14','Wales')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Arabian Gulf League','1148','461','1',1,'16976','FBUAE Arabian Gulf League-14','United Arab Emirates')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Division 1','1146','462','1',1,'16983','FBKSA Division 1-14','Saudi Arabia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('I Liga','1078','386','1',1,'16993','FBPOL I Liga-14','Poland')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Super Liga','1051','391','1',1,'16995','FBSVK Super Liga-14','Slovakia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('1. Liga U19','1014','468','1',1,'16998','FBCZE 1. Liga U19-14','Czech Republic')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('1. SNL','1079','441','1',1,'17002','FBSLO 1.SNL-14','Slovenia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('II Liga','1078','386','1',1,'17003','FBPOL II Liga-14','Poland')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Regionalliga','1024','446','1',1,'17004','FBGER Regionalliga-14','Germany')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('3. Liga','1024','446','1',1,'17005','FBGER 3. Liga-14','Germany')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('UEFA Women´s Champions League','1373','381','1',1,'17015','WFBECUP UEFA Women´s Champions League-14','European Cup')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Super League','1025','394','1',1,'17019','FBGRE Super League-14','Greece')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('1. Liga Promotion','1054','451','1',1,'17025','FBSWI 1. Liga Promotion-14','Switzerland')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Liga I','1048','443','1',1,'17026','FBROM Liga I-14','Romania')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Premier Liga','1200','423','1',1,'17060','FBBIH Premier Liga-14','Bosnia Herzegovina')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Conference National','1018','382','1',1,'17065','FBENG Conference National-14','England')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Conference N / S','1018','382','1',1,'17075','FBENG Conference N / S-14','England')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Regionalliga','1005','383','1',1,'17078','FBAUT Regionalliga-14','Austria')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('3. liga','1014','468','1',1,'17079','FBCZE 3. liga-14','Czech Republic')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Denmark Series','1015','378','1',1,'17086','FBDEN Denmark Series-14','Denmark')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Second Division','1007','377','1',1,'17089','FBBEL Second Division-14','Belgium')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Primeira Liga','1047','418','1',1,'17095','FBPOR Primeira Liga-14','Portugal')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('U21 Premier League','1049','368','1',1,'17099','FBRUS U21 League-14','Russia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('LPF','1363','489','1',1,'17107','FBPAN LPF-14','Panama')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Primera División','1099','399','1',1,'17108','FBCHI Primera Division-14','Chile')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('1. Division','1013','425','1',1,'17109','FBCYP 1. Division-14','Cyprus')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('First League','1197','493','1',1,'17112','FBMNE First League-14','Montenegro')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('U20 League','1039','413','1',1,'17122','FBMEX Under 20 League-14','Mexico')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('U-19 Bundesliga','1024','446','1',1,'17128','FBGER U-19-Bundesliga-14','Germany')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('2. HNL','1012','415','1',1,'17171','FBCRO 2. HNL-14','Croatia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Persha Liga','1056','452','1',1,'17188','FBUKR Persha Liga-14','Ukraine')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Oberliga','1024','446','1',1,'17200','FBGER Oberliga-14','Germany')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('SHL','1070','410','1',1,'17201','ICSWE SHL > Promotion / Relegation Series-14','Sweden')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('SHL','1070','410','1',1,'17206','ICSWE SHL > Quarter-finals-14','Sweden')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Liga Nationala','1130','443','1',1,'17251','HBROM Liga Nationala > Regular Season-14','Romania')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('1.SRL','1214','441','1',1,'17353','HBSLO 1.SRL > Regular Season-14','Slovenia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Premier League','1003','379','1',1,'17360','FBARM Premier League-14','Armenia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('First League','1036','384','1',1,'17361','FBMKD First League-14','Macedonia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Süper Lig','1055','405','1',1,'17363','FBTUR Super Lig-14','Turkey')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('U19 League','1051','391','1',1,'17366','FBSVK U19 League-14','Slovakia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Adriatic League','1088','381','1',1,'17428','BAECUP Adriatic League > Regular Season-14','European Cup')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('LNB Pro A','1125','408','1',1,'17432','BAFRA LNB Pro A > Regular Season-14','France')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Primera Division','1364','557','1',1,'17439','FBSLV Primera Division-14','El Salvador')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Primera B','1099','399','1',1,'17440','FBCHI Primera B-14','Chile')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Ligat ha´Al','1029','365','1',1,'17443','FBISR Ligat ha´Al-14','Israel')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('1. Lig','1055','405','1',1,'17445','FBTUR 1. Lig-14','Turkey')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('DFB Junioren Pokal','1024','446','1',1,'17464','FBGER DFB Junioren Pokal-14','Germany')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('GNF 1','1038','434','1',1,'17465','FBMAR Botola Pro-14','Marocco')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Primera División','1052','438','1',1,'17470','FBSPA Primera Division-14','Spain')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Serie A','1030','398','1',1,'17471','FBITA Serie A-14','Italy')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('2. liga','1051','391','1',1,'17477','FBSVK II Liga-14','Slovakia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Segunda División','1052','438','1',1,'17495','FBSPA Segunda Division-14','Spain')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Landesliga','1005','383','1',1,'17496','FBAUT Landesliga-14','Austria')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('NB II','1026','412','1',1,'17497','FBHUN NB II-14','Hungary')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Feminine Division 1','1438','408','1',1,'17499','WFBFRA Feminine Division 1-14','France')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('U21 League','1026','412','1',1,'17516','FBHUN U21 League-14','Hungary')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('U19 Elite Division','1029','365','1',1,'17517','FBISR U19 Elite Division-14','Israel')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('OHL','1850','385','1',1,'17535','ICCAN OHL > Regular Season-14','Canada')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Elite League','1648','382','1',1,'17541','ICENG Elite League > Regular Season-14','England')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Nationalliga A','1071','451','1',1,'17555','ICSWI Nationalliga A > Semi Finals-14','Switzerland')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Nationalliga A','1071','451','1',1,'17560','ICSWI Nationalliga A > Relegation/Promotion Play Off-14','Switzerland')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('WHL','1850','385','1',1,'17563','ICCAN WHL > Regular Season-14','Canada')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('VHL','1095','368','1',1,'17571','ICRUS VHL > Quarter-finals-14','Russia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Extraliga','1135','391','1',1,'17612','ICSVK Extraliga > Semi Finals-14','Slovakia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('SM-Liiga','1063','403','1',1,'17618','ICFIN SM-Liiga > Quarter-finals-14','Finland')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Primera División Women','1394','438','1',1,'17636','WFBSPA Superliga-14','Spain')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Liga Nacional','1342','480','1',1,'17639','FBHON Liga Nacional-14','Honduras')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('LFPB','1164','429','1',1,'17670','FBBOL LFPB-14','Bolivia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Divizia A','1042','374','1',1,'17674','FBMOL Divizia A-14','Moldova')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('NIFL Reserve League','1043','426','1',1,'17679','FBNIR Reserve League-14','Northern Ireland')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('U19 Ligaen','1015','378','1',1,'17695','FBDEN Danish U19-14','Denmark')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Non League Premier','1018','382','1',1,'17702','FBENG Non League Premier-14','England')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Bundesliga','1112','446','1',1,'17704','HBGER Bundesliga > Regular Season-14','Germany')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Nationalliga A','1208','451','1',1,'17713','HBSWI Nationalliga A > Relegation Round-14','Switzerland')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Nationalliga A','1208','451','1',1,'17716','HBSWI Nationalliga A > Championship Round-14','Switzerland')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('2.Bundesliga','1112','446','1',1,'17725','HBGER 2.Bundesliga > Regular Season-14','Germany')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Liga Asobal','1207','438','1',1,'17733','HBSPA Liga Asobal > Regular Season-14','Spain')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Elit Serien','1093','410','1',1,'17760','HBSWE Elit Serien > Regular Season-14','Sweden')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('EHF Cup','1218','381','1',1,'17763','HBECUP EHF Cup > Group Stage-14','European Cup')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('EHF Champions League','1218','381','1',1,'17805','HBECUP EHF Champions League > Round of 16-14','European Cup')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('1ª Divisão','1127','418','1',1,'17816','HBPOR 1ª Divisão > Relegation Round-14','Portugal')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Super 12','1180','398','1',1,'17822','RGITA Super 12-14','Italy')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Serie B','1030','398','1',1,'17823','FBITA Serie B-14','Italy')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Segunda División','1105','364','1',1,'17845','FBVEN Segunda Division-14','Venezuela')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Stars League','1149','369','1',1,'17850','FBQAT Stars League-14','Qatar')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('U19 League','1056','452','1',1,'17851','FBUKR U19 League-14','Ukraine')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Primera División','1104','402','1',1,'17853','FBURU Primera Division-14','Uruquay')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Elite League','1150','380','1',1,'17857','FBOMA Professional League-14','Oman')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Mestis','1063','403','1',1,'17934','ICFIN Mestis > Quarter-finals-14','Finland')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Extraliga','1341','396','1',1,'17937','ICBLR Extraliga > Final-14','Belarus')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('ACB','1124','438','1',1,'17973','BASPA ACB > Regular Season-14','Spain')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('NBA','1072','436','1',1,'17985','BANBA NBA-14','NBA')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('European Nations Cup','1086','466','1',1,'17993','RGINT European Nations Cup-14','International')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Segunda B','1052','438','1',1,'18003','FBSPA Segunda B-14','Spain')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('CFA','1022','408','1',1,'18012','FBFRA CFA-14','France')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('U21 League 1','1165','469','1',1,'18024','FBALG U21 League 1-14','Algeria')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('','1104','402','1',1,'18034','FBURU Uruguay Reserve League-14','Uruquay')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Allsvenskan','1093','410','1',1,'18042','HBSWE Allsvenskan > Regular Season-14','Sweden')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Ekstraklasa','1267','386','1',1,'18047','HBPOL Ekstraklasa > Regular Season-14','Poland')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('HLA','1206','383','1',1,'18069','HBAUT HLA > Championship Round-14','Austria')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('HLA','1206','383','1',1,'18070','HBAUT HLA > Relegation Round-14','Austria')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('U21 Süper Lig','1055','405','1',1,'18077','FBTUR U21 Super Lig-14','Turkey')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('UEFA U17 Championship','1027','466','1',1,'18079','FBINT UEFA U17 Championship-15','International')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Tercera Division','1052','438','1',1,'18088','FBSPA Tercera Division-14','Spain')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('CFA 2','1022','408','1',1,'18107','FBFRA CFA 2-14','France')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Liga III','1048','443','1',1,'18142','FBROM Liga III-14','Romania')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Liga II','1048','443','1',1,'18143','FBROM Liga II-14','Romania')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Lega Pro 1','1030','398','1',1,'18153','FBITA Lega Pro 1-14','Italy')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('MHL','1095','368','1',1,'18161','ICRUS MHL > Conference - Quarter Finals-14','Russia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Serie A1','1249','398','1',1,'18172','ICITA Serie A1 > Semi Finals-14','Italy')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('NB I','1209','412','1',1,'18178','HBHUN NB I > Relegation Round-14','Hungary')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('NB I','1209','412','1',1,'18179','HBHUN NB I > Championship Round-14','Hungary')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Coupe de France','1119','408','1',1,'18202','HBFRA Coupe de France > Quarter-finals-14','France')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Super League K20','1025','394','1',1,'18244','FBGRE Super League K20-14','Greece')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Campionato Nazionale Primavera','1030','398','1',1,'18245','FBITA Campionato Nazionale Primavera-14','Italy')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('','1092','378','1',1,'18280','HBDEN Division 1-14','Denmark')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Inter-National-League','1158','381','1',1,'18299','ICECUP Inter-National-League > Semi Finals-14','European Cup')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('LHL','1867','370','1',1,'18307','ICLAT LHL > Semi Finals-14','Latvia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('HKFA 2nd Division','1314','479','1',1,'18317','FBHKG HKFA 1st Division-14','Hong Kong')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('','2098','370','1',1,'18318','HBLAT Virsliga-14','Latvia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('','1207','438','1',1,'18422','HBSPA Division de Honor Plata-14','Spain')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('','2026','428','1',1,'18423','HBSRB Superliga-14','Serbia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('','1093','410','1',1,'18424','HBSWE Division 1-14','Sweden')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Lega A Basket','1110','398','1',1,'18469','BAITA Lega A Basket > Regular Season-14','Italy')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Turkiye Basketbol Ligleri','1138','405','1',1,'18475','BATUR Turkiye Basketbol Ligleri > Regular Season-14','Turkey')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Basketball Bundesliga','1137','446','1',1,'18484','BAGER Basketball Bundesliga > Regular Season-14','Germany')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Basket League','1126','394','1',1,'18489','BAGRE Basket League > Regular Season-14','Greece')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Segunda División','1104','402','1',1,'18508','FBURU Segunda Division-14','Uruquay')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Süperlig','1365','405','1',1,'18559','HBTUR Süperlig > Regular Season-14','Turkey')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Serie A','1322','398','1',1,'18572','HBITA Serie A > Championship Round-14','Italy')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('LRL','1571','410','1',1,'18575','HBLTU LRL > Regular Season-14','Sweden')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('A1','1541','394','1',1,'18628','HBGRE A1 > Regular Season-14','Greece')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('AHL','1143','372','1',1,'18853','ICNA AHL > Regular Season-14','North America')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('','1924','412','1',1,'18948','WPHUN OBI-14','Hungary')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('','1914','398','1',1,'19099','WPITA Serie A1-14','Italy')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Premiership','1266','488','1',1,'19187','FBNZL Premiership-14','New Zealand')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Irish Cup','1043','426','1',1,'19214','FBNIR Irish Cup-14','Northern Ireland')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('League Cup','1314','479','1',1,'19333','FBHKG League Cup-14','Hong Kong')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('','1055','405','1',1,'19393','FBTUR TFF 1.Lig U21-14','Turkey')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('EHF Challenge Cup','1218','381','1',1,'19425','HBECUP EHF Challenge Cup > Quarter-finals-14','European Cup')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Pernambucano 1','1009','409','1',1,'19804','FBBRA Pernambucano 1-15','Brazil')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Super 15','1086','466','1',1,'19816','RGINT Super 15-15','International')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('','1176','496','1',1,'19979','BOXING Bouts-15','Boxing')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Paulista A1','1009','409','1',1,'20004','FBBRA Paulista A1-15','Brazil')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Carioca 1','1009','409','1',1,'20005','FBBRA Carioca 1-15','Brazil')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Gaucho 1','1009','409','1',1,'20011','FBBRA Gaucho 1-15','Brazil')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Baiano 1','1009','409','1',1,'20012','FBBRA Baiano 1-15','Brazil')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Mineiro 1','1009','409','1',1,'20013','FBBRA Mineiro 1-15','Brazil')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Cup','1166','447','1',1,'20080','FBZAF Cup-14','South Africa')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Brisbane','1004','454','1',1,'20244','FBAUS Brisbane-15','Australia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('','1122','466','1',1,'20280','WHBINT Friendlies-15','International')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('League Cup','1028','373','1',1,'20311','FBICE League Cup-15','Iceland')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Primera División','1002','467','1',1,'20381','FBARG Primera Division-15','Argentina')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Prim B Nacional','1002','467','1',1,'20382','FBARG Prim B Nacional-15','Argentina')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Meistaradeildin','1020','414','1',1,'20383','FBFAR Meistaradeildin-15','Faroe Islands')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('MLS','1040','406','1',1,'20384','FBMLS MLS-15','Major League Soccer')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Paulista A2','1009','409','1',1,'20390','FBBRA Paulista A2-15','Brazil')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Copa Verde','1009','409','1',1,'20395','FBBRA Copa Verde-15','Brazil')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('CAF Champions League','1184','508','1',1,'20398','FBAFCUP CAF Champions League-15','African Cup')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Sudamericano U17','1027','466','1',1,'20403','FBINT Sudamericano U17-15','International')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Six Nations','1086','466','1',1,'20410','RGINT 6 Nations-15','International')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Premier Division','1098','435','1',1,'20518','FBIRE Premier Division-15','Ireland')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Brisbane Capital League 1','1004','454','1',1,'20519','FBAUS Brisbane Capital League 1-15','Australia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Paulista A3','1009','409','1',1,'20520','FBBRA Paulista A3-15','Brazil')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('I-League','1286','481','1',1,'20521','FBIND I-League-14','India')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Club Friendlies','1017','381','1',1,'20526','FBECUP Club Friendlies-15','European Cup')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Paranaense 1','1009','409','1',1,'21355','FBBRA Paranaense 1-15','Brazil')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Goiano 1','1009','409','1',1,'21356','FBBRA Goiano 1-15','Brazil')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Catarinense 1','1009','409','1',1,'21373','FBBRA Catarinense 1-15','Brazil')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Division Profesional','1096','448','1',1,'21438','FBPAR Division Profesional-15','Paraguay')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Other Competition Matches','1017','381','1',1,'21441','FBECUP Other Competition Matches-15','European Cup')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('','1310','483','1',1,'22193','FBJAM Super League-14','Jamaica')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Maranhense','1009','409','1',1,'22219','FBBRA Maranhense-15','Brazil')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('FA Cup','1156','393','1',1,'22285','FBMYS FA Cup-15','Malaysia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Primera A','1100','389','1',1,'22472','FBCOL Primera A-15','Colombia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Meistriliiga','1019','411','1',1,'22485','FBEST Meistriliiga-15','Estonia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Esiliiga A','1019','411','1',1,'22486','FBEST Esiliiga A-15','Estonia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Primera A','1163','433','1',1,'22497','FBECU Primera A-15','Ecuador')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('S.League','1121','404','1',1,'22498','FBSGP S-League-15','Singapore')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Copa Inca','1045','457','1',1,'22521','FBPER Copa Inca-15','Peru')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('','1096','448','1',1,'22565','FBPAR Primera Reserves-15','Paraguay')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Carioca 2','1009','409','1',1,'22577','FBBRA Carioca 2-15','Brazil')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Challenge Cup','1434','381','1',1,'22582','RLECUP Challenge Cup-15','European Cup')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('','1210','468','1',1,'22584','HBCZE Cup-14','Czech Republic')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('UFL','1406','533','1',1,'22607','FBPHL UFL-15','Philippines')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('J2 League','1031','416','1',1,'22608','FBJPN J2 League-15','Japan')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Japan Football League','1031','416','1',1,'22609','FBJPN Japan Football League-15','Japan')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('J3 League','1031','416','1',1,'22610','FBJPN J3 League-15','Japan')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('CSL','1097','424','1',1,'22722','FBCHN CSL-15','China')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('First Division','1098','435','1',1,'22726','FBIRE First Division-15','Ireland')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('National Premier League','1004','454','1',1,'22742','FBAUS National Premier League-15','Australia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Prim B Metro','1002','467','1',1,'22756','FBARG Prim B Metro-15','Argentina')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Prim C Metro','1002','467','1',1,'22832','FBARG Primera C-15','Argentina')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('K League Classic','1120','437','1',1,'22845','FBKOR K-League Classic-15','South Korea')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('K League Challenge','1120','437','1',1,'22846','FBKOR K League Challenge-15','South Korea')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Thai Division 2 League','1153','388','1',1,'22848','FBTHA Thai Division 2 League-15','Thailand')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Suomen Cup','1021','403','1',1,'22849','FBFIN Suomen Cup-15','Finland')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Victoria Division One','1004','454','1',1,'23731','FBAUS Victoria Division 1-15','Australia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('A Lyga','1034','401','1',1,'23743','FBLTU A Lyga-15','Lithuania')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('','1004','454','1',1,'23746','FBAUS Western Night Series-15','Australia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('National Rugby League','1479','454','1',1,'23760','RLAUS National Rugby League-15','Australia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Primera B','1163','433','1',1,'23839','FBECU Primera B-15','Ecuador')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Premier League','1102','445','1',1,'23840','FBKAZ Premier League-15','Kazakhstan')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Virsliga','1032','370','1',1,'23942','FBLAT Virsliga-15','Latvia')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('','1891','438','1',1,'24042','FSSPA Segunda Division-14','Spain')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('National League','1120','437','1',1,'24049','FBKOR National League-15','South Korea')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('Challengers League','1120','437','1',1,'24076','FBKOR K3 League-15','South Korea')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('China League One','1097','424','1',1,'24104','FBCHN China League One-15','China')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('','1122','466','1',1,'24199','WHBINT Asian Championships-15','International')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('','1878','466','1',1,'24224','FSINT UEFA Futsal Championship - Qualification-15','International')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('USL Pro / MLS Reserve','1157','455','1',1,'24239','FBUSL USL Pro-15','United Soccer Leagues')
INSERT INTO Sports(Name, League, Country, Code, Active, ProviderID, InternalName, CountryName) Values ('','1646','363','1',1,'24344','HBBUL Cup-14','Bulgaria')
