//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADOL.APP.CurrentAccountService.BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportBet
    {
        public SportBet()
        {
            this.UserBets = new HashSet<UserBet>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
        public decimal Odd1 { get; set; }
        public Nullable<decimal> Odd2 { get; set; }
        public Nullable<decimal> Odd3 { get; set; }
        public Nullable<decimal> Odd4 { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public int SportEventID { get; set; }
    
        public virtual SportEvent SportEvent { get; set; }
        public virtual ICollection<UserBet> UserBets { get; set; }
    }
}
