//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADOL.APP.CurrentAccountService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserBets = new HashSet<UserBet>();
        }
    
        public int ID { get; set; }
        public string UID { get; set; }
        public string NickName { get; set; }
        public string SessionToken { get; set; }
        public string LaunchToken { get; set; }
        public decimal Balance { get; set; }
    
        public virtual ICollection<UserBet> UserBets { get; set; }
    }
}
